Components:
  - "src/Components/**"

Hooks:
  - "src/hooks/**"

Utilities:
  - "src/utilities/**"
  - "src/types/**"

Docs:
  - "docs/**"
  - "*.md"

Dependencies:
  - "package.json"
  - "yarn.lock"
  - "package-lock.json"
